name: Update Player Cards

on:
  workflow_dispatch:  # nur manuell starten über GitHub UI

jobs:
  update-cards:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      - name: Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Abhängigkeiten installieren
        run: npm ci

      - name: Skript ausführen
        run: node scripts/update-json.js

      - name: Änderungen committen und pushen
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add static/cards.json
          if git diff --cached --quiet; then
            echo "Keine Änderungen – cards.json ist gleich."
          else
            git commit -m "Update cards.json via GitHub Actions"
            git push origin master
